import fs from 'node:fs';import {gzipSync,gunzipSync}from 'node:zlib';import{createHash}from'node:crypto';import{decodeRoomBundle}from'./dist/geometry-pack.js';import{MeshoptEncoder as Encoder}from'./tools/meshoptimizer/meshopt_encoder.js';import{MeshoptSimplifier as Simplifier}from'./tools/meshoptimizer/meshopt_simplifier.js';import{MeshoptDecoder as Decoder}from'./dist/vendor/meshopt_decoder.mjs';import{createGraph}from'./dist/graph.js';
await Promise.all([Encoder.ready,Simplifier.ready,Decoder.ready]);const source=gunzipSync(fs.readFileSync('dist/room.bundle.gz')),pack=decodeRoomBundle(source.buffer.slice(source.byteOffset,source.byteOffset+source.byteLength)),graph=createGraph(pack.document),mode=process.argv[2]??'balanced';
let textGeometry=false;const geometries={},buffers={},parts=[],rows=[],dedup=new Map();let offset=0;
function register(data,spec){const hash=createHash('sha256').update(data).update(JSON.stringify(spec)).digest('hex'),file=dedup.get(hash)??('b'+dedup.size.toString(36));if(!buffers[file]){dedup.set(hash,file);buffers[file]={offset,length:data.length,...spec};parts.push(Buffer.from(data));offset+=data.length;}return file;}
function store(array,itemSize,name){const count=array.length/itemSize;let data=new Uint8Array(array.buffer,array.byteOffset,array.byteLength),filter,codec='raw',stride=itemSize*array.BYTES_PER_ELEMENT,dequant;
 if(textGeometry&&array instanceof Float32Array){const dictionary=Array.from({length:itemSize},(_,k)=>[...new Set(Array.from({length:count},(_,i)=>array[i*itemSize+k]))].sort((a,b)=>a-b)),lookups=dictionary.map(values=>new Map(values.map((v,i)=>[v,i]))),components=Math.ceil(itemSize/2)*2;if(dictionary.some(d=>d.length>65535))throw Error('Text dictionary too large');const values=new Uint16Array(count*components);for(let i=0;i<count;i++)for(let k=0;k<itemSize;k++)values[i*components+k]=lookups[k].get(array[i*itemSize+k]);data=new Uint8Array(values.buffer);stride=components*2;const flat=Float32Array.from(dictionary.flat()),encoded=Encoder.encodeVertexBuffer(new Uint8Array(flat.buffer),flat.length,4),table=register(encoded,{codec:'vertex',count:flat.length,stride:4,decodedBytes:flat.byteLength});let start=0;const offsets=dictionary.map(values=>{const result=start;start+=values.length;return result;});dequant={table,offsets,itemSize,components};}
 else if(array instanceof Float32Array&&['normal','extrudeNormal'].includes(name)){const values=new Float32Array(count*4);for(let i=0;i<count;i++){const x=array[i*3],y=array[i*3+1],z=array[i*3+2],len=Math.hypot(x,y,z);if(len>1e-12){values[i*4]=x/len;values[i*4+1]=y/len;values[i*4+2]=z/len;values[i*4+3]=1;}}data=Encoder.encodeFilterOct(values,count,8,10);stride=8;filter='OCTAHEDRAL';dequant={oct:true};}
 else if(array instanceof Float32Array){const bits=name==='position'?(textGeometry?20:16):name==='uv'?16:10,levels=2**bits-1,min=Array(itemSize).fill(Infinity),max=Array(itemSize).fill(-Infinity);for(let i=0;i<array.length;i++){const k=i%itemSize;min[k]=Math.min(min[k],array[i]);max[k]=Math.max(max[k],array[i]);}const signed=['normal','extrudeNormal'].includes(name);const scale=max.map((v,k)=>signed?Math.max(Math.abs(v),Math.abs(min[k]))/(2**(bits-1)-1):(v-min[k])/levels);if(signed)min.fill(0);const components=bits>16?itemSize:Math.ceil(itemSize/2)*2,values=new (bits>16?Uint32Array:signed?Int16Array:Uint16Array)(count*components);for(let i=0;i<count;i++)for(let k=0;k<itemSize;k++)values[i*components+k]=scale[k]?Math.round((array[i*itemSize+k]-min[k])/scale[k]):0;data=new Uint8Array(values.buffer);stride=components*values.BYTES_PER_ELEMENT;dequant={min,scale,itemSize,components,signed,wide:bits>16};}
 const decodedBytes=data.length;if(stride%4===0&&name!=='index'){data=Encoder.encodeVertexBuffer(data,count,stride);codec='vertex';}else if(name==='index'){data=textGeometry?Encoder.encodeIndexSequence(data,count,stride):Encoder.encodeIndexBuffer(data,count,stride);codec=textGeometry?'index':'triangles';}
 const file=register(data,{decodedBytes,count,stride,filter,codec,dequant});
 return {file,type:array.constructor.name,itemSize,count};}

for(const [file,original]of Object.entries(pack.geometries)){
 const g=structuredClone(original),attributes=Object.fromEntries(Object.entries(g.attributes).map(([k,a])=>[k,new globalThis[a.type](pack.array(a,globalThis[a.type]))]));let indices=g.index?Uint32Array.from(pack.array(g.index,globalThis[g.index.type])):Uint32Array.from({length:g.attributes.position.count},(_,i)=>i),before=indices.length,error=0;
 const owners=[...graph.records.values()].filter(r=>r.current._geometry===file),names=owners.map(r=>{let o=r.object,n=[];while(o?.parent){n.unshift(o.name);o=o.parent;}return n.join('/');}),shadowOnly=names.every(n=>n.includes('Shadow')||n.includes('Deleted Components'));
 textGeometry=owners.some(r=>r.current.geometry?.type==='TextGeometry');
 if(!textGeometry&&mode!=='quantize'&&indices.length>6000&&!(g.groups?.length)&&!Object.keys(g.morphAttributes??{}).length){
  const list=['normal','extrudeNormal','uv'].filter(k=>attributes[k]),weights=list.flatMap(k=>Array(g.attributes[k].itemSize).fill(k==='uv'?2:shadowOnly?.05:.5)),stride=weights.length,values=new Float32Array(g.attributes.position.count*stride);
  for(let v=0;v<g.attributes.position.count;v++){let p=v*stride;for(const k of list)for(let j=0;j<g.attributes[k].itemSize;j++)values[p++]=attributes[k][v*g.attributes[k].itemSize+j];}
  [indices,error]=Simplifier.simplifyWithAttributes(indices,attributes.position,3,values,stride,weights,null,Math.floor(before*(shadowOnly?.025:.15)/3)*3,names.some(n=>n.includes('/Watch/'))?.00025:shadowOnly?.0005:.001,['Permissive']);
 }
 const [remap,count]=!textGeometry&&!(g.groups?.length)&&!Object.keys(g.morphAttributes??{}).length?Encoder.reorderMesh(indices,true,true):Simplifier.compactMesh(indices);for(const [k,old]of Object.entries(attributes)){const n=g.attributes[k].itemSize,a=new old.constructor(count*n);for(let i=0;i<remap.length;i++)if(remap[i]!==0xffffffff)a.set(old.subarray(i*n,(i+1)*n),remap[i]*n);attributes[k]=a;g.attributes[k]={...g.attributes[k],...store(a,n,k)};}
 const Index=count<=65535?Uint16Array:Uint32Array;g.index=store(new Index(indices),1,'index');
 for(const [k,list]of Object.entries(g.morphAttributes??{}))for(let i=0;i<list.length;i++){const a=list[i],old=pack.array(a,globalThis[a.type]),n=a.itemSize,data=new old.constructor(count*n);for(let j=0;j<remap.length;j++)if(remap[j]!==0xffffffff)data.set(old.subarray(j*n,(j+1)*n),remap[j]*n);list[i]={...a,...store(data,n,k)};}
 // Conservative original bounds expanded for the position quantization grid.
 const max=Math.max(...g.bounds.flat().map(Math.abs)),margin=Math.max(1e-6,max/2**14);g.bounds=[g.bounds[0].map(v=>v-margin),g.bounds[1].map(v=>v+margin)];if(g.sphere)g.sphere[1]+=margin*2;
 geometries[file]=g;rows.push({file,names,beforeTriangles:before/3,afterTriangles:indices.length/3,beforeVertices:original.attributes.position.count,afterVertices:count,error,shadowOnly});
}
const metadataText=JSON.stringify({version:5,document:pack.document,geometries,buffers}),strings=new Map();for(const [token]of metadataText.matchAll(/"(?:[^"\\]|\\.)*"/g))strings.set(token,(strings.get(token)??0)+1);
const dictionary=[...strings].filter(([token,count])=>(token.length>12&&count>1)||/^"~q\d+"$/.test(token)).map(([token])=>token),lookup=new Map(dictionary.map((token,i)=>[token,i])),packed=metadataText.replace(/"(?:[^"\\]|\\.)*"/g,token=>lookup.has(token)?JSON.stringify('~q'+lookup.get(token)):token);
const meta=Buffer.from(JSON.stringify({dictionary,packed})),header=Buffer.alloc(8);header.write('RMC5');header.writeUInt32LE(meta.length,4);const raw=Buffer.concat([header,meta,...parts]),encoded=gzipSync(raw,{level:9});fs.writeFileSync('dist/room.compact.gz',encoded);const hash=createHash('sha256').update(encoded).digest('hex').slice(0,20),bundleURL='./room.compact.gz?v='+hash;fs.writeFileSync('dist/bundle-version.js','export const bundleURL='+JSON.stringify(bundleURL)+';\n');const html=fs.readFileSync('dist/index.html','utf8').replace(/const url="\.\/room\.(?:bundle|compact)\.gz\?v=[^"]+"/,'const url='+JSON.stringify(bundleURL));fs.writeFileSync('dist/index.html',html);
const report={mode,bytes:encoded.length,rawBytes:raw.length,trianglesBefore:rows.reduce((s,r)=>s+r.beforeTriangles,0),trianglesAfter:rows.reduce((s,r)=>s+r.afterTriangles,0),verticesBefore:rows.reduce((s,r)=>s+r.beforeVertices,0),verticesAfter:rows.reduce((s,r)=>s+r.afterVertices,0),rows};fs.writeFileSync('qa/compact-geometry-results.json',JSON.stringify(report,null,2));console.log({...report,rows:undefined});
