import fs from "node:fs";
import path from "node:path";
const base = path.resolve(".cache/conversion"),
  dist = path.join(base, "dist"),
  keep = new Set();
function references(value) {
  if (typeof value === "string") {
    if (value.startsWith("assets/")) keep.add(value);
  } else if (Array.isArray(value)) {
    for (const v of value) references(v);
  } else if (value && typeof value === "object") {
    for (const v of Object.values(value)) references(v);
  }
}
for (const name of ["scene.json", "room.json"])
  references(JSON.parse(fs.readFileSync(path.join(dist, name))));
// Code literals also include fonts and the original console animation/audio.
function codeFiles(folder) {
  for (const entry of fs.readdirSync(folder, { withFileTypes: true })) {
    const file = path.join(folder, entry.name);
    if (entry.isDirectory()) codeFiles(file);
    else if (/\.(?:js|html|css)$/.test(entry.name))
      for (const match of fs
        .readFileSync(file, "utf8")
        .matchAll(/assets\/[A-Za-z0-9_./-]+/g))
        keep.add(match[0]);
  }
}
codeFiles(dist);
const manifest = JSON.parse(
  fs.readFileSync(path.join(dist, "geometry-pack.json")),
);
for (const file of Object.keys(manifest.geometries)) keep.add(file);
const removed = [];
for (const entry of fs.readdirSync(path.join(dist, "assets"), {
  withFileTypes: true,
})) {
  if (!entry.isFile()) continue;
  const file = "assets/" + entry.name;
  if (keep.has(file)) continue;
  const bytes = fs.statSync(path.join(dist, file)).size;
  removed.push({
    file,
    bytes,
    reason: manifest.buffers[file]
      ? "Duplicate raw buffer: available in compressed geometry pack"
      : "No document, compiled geometry or code reference",
  });
  fs.unlinkSync(path.join(dist, file));
}
for (const file of keep)
  if (!fs.existsSync(path.join(dist, file)))
    throw Error("Referenced asset is missing: " + file);
fs.rmSync(path.join(dist, "geometry-pack.bin.gz"), { force: true });
const output = {
  scope:
    "Keep complete source/editable documents, compiled metadata, fonts, hidden-state resources and code literals including the console Easter egg. Runtime buffer bytes remain in the compressed archive; raw duplicates are regenerated by compile.mjs.",
  removed,
  removedBytes: removed.reduce((sum, x) => sum + x.bytes, 0),
  retainedFiles: keep.size,
};
fs.writeFileSync(
  path.join(base, "qa/asset-pruning.json"),
  JSON.stringify(output, null, 2),
);
console.log({
  removedFiles: removed.length,
  removedBytes: output.removedBytes,
  retainedFiles: keep.size,
});
