#!/usr/bin/env python3
"""Standalone splineformat CLI. Generated by tools/package_results.py."""


# Source module: splineformat/codec.py
"""Independent reader/writer for the MessagePack dialect in the supplied scene.

Records become Python dictionaries. Extensions remain explicit so that Spline
classes, binary types and structured-clone references survive an export/import.
No Spline runtime code is executed by this module.
"""

from collections import Counter
from dataclasses import dataclass
import struct


class FormatError(ValueError):
    pass


class BigInt(int):
    """A 64-bit integer that this msgpackr reader exposes as JavaScript BigInt."""


@dataclass
class Extension:
    code: int
    payload: object
    following: object = None


@dataclass
class Map:
    """MessagePack map, distinct from msgpackr's object records."""

    pairs: list


FOLLOWING = {1, 2, 3, 4, 5, 6, 101, 105, 115, 120}
TYPED_ARRAYS = (
    "Int8Array", "Uint8Array", "Uint8ClampedArray", "Int16Array",
    "Uint16Array", "Int32Array", "Uint32Array", "Float32Array",
    "Float64Array", "BigInt64Array", "BigUint64Array",
)


class Decoder:
    def __init__(self, data, *, max_depth=300):
        self.data = memoryview(data)
        self.offset = 0
        self.max_depth = max_depth
        self.structures = {}
        self.extensions = Counter()
        self.record_definitions = 0
        self.binary_bytes = 0
        self.binary_count = 0

    def fail(self, message):
        raise FormatError(f"{message} at byte {self.offset} (0x{self.offset:x})")

    def take(self, size):
        end = self.offset + size
        if size < 0 or end > len(self.data):
            self.fail(f"truncated value: need {size} bytes")
        value = self.data[self.offset:end]
        self.offset = end
        return value

    def number(self, fmt):
        return struct.unpack(">" + fmt, self.take(struct.calcsize(fmt)))[0]

    def count(self, count, minimum=1):
        if count * minimum > len(self.data) - self.offset:
            self.fail(f"container length {count} exceeds remaining data")
        return count

    def decode(self):
        value = self.read()
        if self.offset != len(self.data):
            self.fail("trailing bytes after root value")
        return value

    def record(self, index, depth):
        keys = self.structures[index]
        return {key: self.read(depth + 1) for key in keys}

    def extension(self, size, depth):
        code = self.number("B")
        payload = self.take(size)
        self.extensions[code] += 1
        if code == 0x72:
            if size != 1:
                self.fail("only one-byte record definitions are currently supported")
            low = payload[0] & 63
            keys = self.read(depth + 1)
            if not isinstance(keys, list) or not all(isinstance(k, str) for k in keys):
                self.fail("record keys must be an array of strings")
            if len(keys) != len(set(keys)):
                self.fail("duplicate record keys are not supported")
            self.structures[low] = keys
            self.record_definitions += 1
            return self.record(low, depth)
        if code == 0x62:
            self.fail("msgpackr bundled strings are not supported")
        if code in FOLLOWING:
            expected = 4 if code == 105 else 1
            if size != expected:
                self.fail(f"extension {code} requires {expected} payload bytes")
            return Extension(code, payload, self.read(depth + 1))
        if code == 0 and size != 1:
            self.fail("undefined extension requires one payload byte")
        if code == 112 and size != 4:
            self.fail("reference extension requires four payload bytes")
        if code == 116:
            if not size or payload[0] >= len(TYPED_ARRAYS):
                self.fail("unsupported typed array type")
            item_size = (1, 1, 1, 2, 2, 4, 4, 4, 8, 8, 8)[payload[0]]
            if (size - 1) % item_size:
                self.fail("typed array payload has a partial element")
        if code not in {0, 112, 116, 255}:
            self.fail(f"unsupported extension {code}")
        return Extension(code, payload)

    def read(self, depth=0):
        if depth > self.max_depth:
            self.fail("nesting limit exceeded")
        token = self.number("B")
        if token < 128:
            index = token & 63
            if token >= 64 and index in self.structures:
                return self.record(index, depth)
            return token
        if token >= 224:
            return token - 256
        if 160 <= token < 192:
            return self.string(token - 160)
        if 144 <= token < 160:
            return self.array(token - 144, depth)
        if 128 <= token < 144:
            return self.map(token - 128, depth)
        if token == 192:
            return None
        if token in (194, 195):
            return token == 195
        formats = {202: "f", 203: "d", 204: "B", 205: "H", 206: "I", 207: "Q", 208: "b", 209: "h", 210: "i", 211: "q"}
        if token in formats:
            value = self.number(formats[token])
            return BigInt(value) if token in (207, 211) else value
        if token in (196, 197, 198):
            size = self.number({196: "B", 197: "H", 198: "I"}[token])
            value = self.take(size)
            self.binary_count += 1
            self.binary_bytes += size
            return value
        if token in (217, 218, 219):
            return self.string(self.number({217: "B", 218: "H", 219: "I"}[token]))
        if token in (220, 221):
            return self.array(self.number("H" if token == 220 else "I"), depth)
        if token in (222, 223):
            return self.map(self.number("H" if token == 222 else "I"), depth)
        if 212 <= token <= 216:
            return self.extension(1 << (token - 212), depth)
        if token in (199, 200, 201):
            return self.extension(self.number({199: "B", 200: "H", 201: "I"}[token]), depth)
        self.fail(f"unsupported MessagePack token 0x{token:02x}")

    def string(self, size):
        try:
            return bytes(self.take(size)).decode("utf-8")
        except UnicodeDecodeError as error:
            self.fail(f"invalid UTF-8: {error.reason}")

    def array(self, size, depth):
        return [self.read(depth + 1) for _ in range(self.count(size))]

    def map(self, size, depth):
        return Map([(self.read(depth + 1), self.read(depth + 1)) for _ in range(self.count(size, 2))])


class Encoder:
    """Write inline records to avoid relying on external structure dictionaries."""

    def __init__(self, stream):
        self.stream = stream

    def write(self, data):
        self.stream.write(data)

    def number(self, token, fmt, value):
        self.write(bytes([token]) + struct.pack(">" + fmt, value))

    def sized(self, size, short, medium, long):
        if size < 256 and short is not None:
            self.number(short, "B", size)
        elif size < 65536:
            self.number(medium, "H", size)
        else:
            self.number(long, "I", size)

    def extension(self, code, payload):
        size = len(payload)
        fixed = {1: 212, 2: 213, 4: 214, 8: 215, 16: 216}
        if size in fixed:
            self.write(bytes([fixed[size]]))
        else:
            self.sized(size, 199, 200, 201)
        self.write(bytes([code]))
        self.write(payload)

    def encode(self, value, depth=0):
        if depth > 300:
            raise FormatError("nesting limit exceeded while encoding")
        if value is None:
            self.write(b"\xc0")
        elif isinstance(value, bool):
            self.write(b"\xc3" if value else b"\xc2")
        elif isinstance(value, BigInt):
            if 0 <= value < 2**64:
                self.number(207, "Q", value)
            elif -2**63 <= value < 0:
                self.number(211, "q", value)
            else:
                raise FormatError("BigInt outside MessagePack 64-bit range")
        elif isinstance(value, int):
            # 0x40..0x7f are record IDs once a record exists.
            if 0 <= value < 64 or -32 <= value < 0:
                self.write(bytes([value & 255]))
            elif 0 <= value < 256:
                self.number(204, "B", value)
            elif 0 <= value < 65536:
                self.number(205, "H", value)
            elif 0 <= value < 2**32:
                self.number(206, "I", value)
            elif 0 <= value < 2**64:
                self.number(207, "Q", value)
            elif -128 <= value < 0:
                self.number(208, "b", value)
            elif -32768 <= value < 0:
                self.number(209, "h", value)
            elif -2**31 <= value < 0:
                self.number(210, "i", value)
            elif -2**63 <= value < 0:
                self.number(211, "q", value)
            else:
                raise FormatError("integer outside MessagePack 64-bit range")
        elif isinstance(value, float):
            self.number(203, "d", value)
        elif isinstance(value, str):
            data = value.encode("utf-8")
            if len(data) < 32:
                self.write(bytes([160 + len(data)]))
            else:
                self.sized(len(data), 217, 218, 219)
            self.write(data)
        elif isinstance(value, (bytes, bytearray, memoryview)):
            self.sized(len(value), 196, 197, 198)
            self.write(value)
        elif isinstance(value, Extension):
            self.extension(value.code, value.payload)
            if value.code in FOLLOWING:
                self.encode(value.following, depth + 1)
        elif isinstance(value, dict):
            if not all(isinstance(k, str) for k in value):
                raise FormatError("object record keys must be strings")
            self.extension(114, b"\x40")
            self.encode(list(value), depth + 1)
            for item in value.values():
                self.encode(item, depth + 1)
        elif isinstance(value, Map):
            if len(value.pairs) < 16:
                self.write(bytes([128 + len(value.pairs)]))
            else:
                self.sized(len(value.pairs), None, 222, 223)
            for key, item in value.pairs:
                self.encode(key, depth + 1)
                self.encode(item, depth + 1)
        elif isinstance(value, list):
            if len(value) < 16:
                self.write(bytes([144 + len(value)]))
            else:
                self.sized(len(value), None, 220, 221)
            for item in value:
                self.encode(item, depth + 1)
        else:
            raise FormatError(f"cannot encode {type(value).__name__}")


# Source module: splineformat/document.py
"""Reversible JSON representation and scene inventory."""

import base64
from array import array
from collections import Counter
import hashlib
import math
from pathlib import Path
import sys



ARRAY_FORMATS = {
    "u8": ("B", 1), "i8": ("b", 1), "u16le": ("H", 2), "i16le": ("h", 2),
    "u32le": ("I", 4), "i32le": ("i", 4), "i64le": ("q", 8), "f64le": ("d", 8),
}


def media_suffix(data):
    head = bytes(data[:32])
    if head.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if head.startswith(b"\xff\xd8\xff"):
        return "jpg"
    if head.startswith((b"GIF87a", b"GIF89a")):
        return "gif"
    if head.startswith(b"RIFF"):
        return {b"WEBP": "webp", b"WAVE": "wav"}.get(head[8:12], "bin")
    if head[4:8] == b"ftyp":
        return "mp4"
    if head.startswith(b"OggS"):
        return "ogg"
    if head.startswith(b"ID3") or len(head) >= 2 and head[0] == 255 and head[1] & 224 == 224:
        return "mp3"
    if head.startswith(b"DRACO"):
        return "drc"
    return "bin"


def tag(kind, **values):
    return {"$spline": {"kind": kind, **values}}


class JsonExport:
    def __init__(self, directory):
        self.directory = Path(directory)
        self.assets = {}

    def asset(self, data, suffix=None):
        digest = hashlib.sha256(data).hexdigest()
        filename = f"assets/{digest}.{suffix or media_suffix(data)}"
        if filename not in self.assets:
            path = self.directory / filename
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            self.assets[filename] = {"file": filename, "bytes": len(data), "sha256": digest}
        return filename

    def convert(self, value):
        if isinstance(value, BigInt):
            return tag("bigint", value=str(value))
        if isinstance(value, Extension):
            fields = {"code": value.code, "payload": self.convert(value.payload)}
            if value.code in FOLLOWING:
                fields["value"] = self.convert(value.following)
            return tag("extension", **fields)
        if isinstance(value, Map):
            return tag("map", pairs=[[self.convert(k), self.convert(v)] for k, v in value.pairs])
        if isinstance(value, (bytes, bytearray, memoryview)):
            if len(value) <= 32:
                return tag("bytes", base64=base64.b64encode(value).decode("ascii"))
            return tag("bytes", file=self.asset(value))
        if isinstance(value, float) and not math.isfinite(value):
            return tag("float", value=repr(value))
        # Keep large integer precision when a JSON editor uses IEEE-754 numbers.
        if isinstance(value, int) and not isinstance(value, bool) and abs(value) > 2**53 - 1:
            return tag("integer", value=str(value))
        if isinstance(value, str) and len(value) > 4096:
            if value.startswith("data:") and ";base64," in value[:256]:
                prefix, encoded = value.split(",", 1)
                try:
                    binary = base64.b64decode(encoded, validate=True)
                except ValueError:
                    binary = None
                if binary is not None and base64.b64encode(binary).decode("ascii") == encoded:
                    return tag("data-uri", prefix=prefix + ",", file=self.asset(binary))
            return tag("text", file=self.asset(value.encode("utf-8"), "txt"))
        if isinstance(value, dict):
            if "$spline" in value:
                return tag("object", pairs=[[k, self.convert(v)] for k, v in value.items()])
            return {k: self.convert(v) for k, v in value.items()}
        if isinstance(value, list):
            if len(value) >= 128 and all(
                type(v) is float or type(v) is int and abs(v) <= 2**53 - 1
                for v in value
            ):
                integers = all(type(v) is int for v in value)
                fmt = "f64le"
                if integers:
                    low, high = min(value), max(value)
                    for fmt, minimum, maximum in (
                        ("u8", 0, 255), ("i8", -128, 127), ("u16le", 0, 65535),
                        ("i16le", -32768, 32767), ("u32le", 0, 2**32 - 1),
                        ("i32le", -2**31, 2**31 - 1), ("i64le", -2**63, 2**63 - 1),
                    ):
                        if minimum <= low and high <= maximum:
                            break
                typecode, width = ARRAY_FORMATS[fmt]
                numbers = array(typecode, value)
                if numbers.itemsize != width:
                    raise FormatError("unsupported platform numeric array width")
                if sys.byteorder != "little":
                    numbers.byteswap()
                raw = numbers.tobytes()
                suffix = "drc" if fmt in ("u8", "i8") and raw.startswith(b"DRACO") else fmt
                return tag("number-array", format=fmt, count=len(value), file=self.asset(raw, suffix))
            return [self.convert(v) for v in value]
        return value


class JsonImport:
    def __init__(self, directory):
        self.directory = Path(directory).resolve()
        self.cache = {}

    def asset(self, filename):
        path = (self.directory / filename).resolve()
        if not path.is_relative_to(self.directory):
            raise FormatError("asset path must stay inside the decoded directory")
        if path not in self.cache:
            self.cache[path] = path.read_bytes()
        return self.cache[path]

    def convert(self, value):
        if isinstance(value, list):
            return [self.convert(v) for v in value]
        if not isinstance(value, dict):
            return value
        if "$spline" not in value:
            return {k: self.convert(v) for k, v in value.items()}
        spec = value["$spline"]
        kind = spec["kind"]
        if kind == "bytes":
            return self.asset(spec["file"]) if "file" in spec else base64.b64decode(spec["base64"], validate=True)
        if kind == "text":
            return self.asset(spec["file"]).decode("utf-8")
        if kind == "data-uri":
            return spec["prefix"] + base64.b64encode(self.asset(spec["file"])).decode("ascii")
        if kind == "number-array":
            if spec["format"] not in ARRAY_FORMATS:
                raise FormatError("unknown numeric array format")
            typecode, width = ARRAY_FORMATS[spec["format"]]
            raw = self.asset(spec["file"])
            if len(raw) != spec["count"] * width:
                raise FormatError("numeric array byte count does not match")
            numbers = array(typecode)
            if numbers.itemsize != width:
                raise FormatError("unsupported platform numeric array width")
            numbers.frombytes(raw)
            if sys.byteorder != "little":
                numbers.byteswap()
            return numbers.tolist()
        if kind == "integer":
            return int(spec["value"])
        if kind == "bigint":
            return BigInt(spec["value"])
        if kind == "float":
            if spec["value"] not in ("nan", "inf", "-inf"):
                raise FormatError("invalid tagged float")
            return float(spec["value"])
        if kind == "extension":
            code = spec["code"]
            if not isinstance(code, int) or code not in FOLLOWING | {0, 112, 116, 255}:
                raise FormatError(f"unsupported JSON extension {code!r}")
            payload = self.convert(spec["payload"])
            if not isinstance(payload, bytes):
                raise FormatError("extension payload must be bytes")
            return Extension(code, payload, self.convert(spec["value"]) if code in FOLLOWING else None)
        if kind == "map":
            return Map([(self.convert(k), self.convert(v)) for k, v in spec["pairs"]])
        if kind == "object":
            return {k: self.convert(v) for k, v in spec["pairs"]}
        raise FormatError(f"unknown JSON tag {kind!r}")


def walk(root):
    """Visit stored values once, leaving reference edges unexpanded."""
    pending = [root]
    while pending:
        value = pending.pop()
        yield value
        if isinstance(value, dict):
            pending.extend(value.values())
        elif isinstance(value, list):
            pending.extend(value)
        elif isinstance(value, Extension) and value.code in FOLLOWING:
            pending.append(value.following)
        elif isinstance(value, Map):
            for key, item in value.pairs:
                pending.extend((key, item))


class SceneView:
    def __init__(self, root):
        self.root = root
        self.references = {}
        self.data_uris = Counter()
        self.media = Counter()
        self.large_strings = []
        for value in walk(root):
            if isinstance(value, Extension) and value.code == 105:
                self.references[int.from_bytes(value.payload, "big")] = value.following
            elif isinstance(value, str):
                if value.startswith("data:"):
                    self.data_uris[value.split(",", 1)[0]] += 1
                if len(value) > 4096:
                    self.large_strings.append(len(value))
            elif isinstance(value, (bytes, bytearray, memoryview)):
                self.media[media_suffix(value)] += 1

    def unwrap(self, value):
        seen = set()
        while isinstance(value, Extension):
            if id(value) in seen:
                raise FormatError("cyclic extension wrapper")
            seen.add(id(value))
            if value.code in {1, 2, 3, 4, 5, 6, 105}:
                value = value.following
            elif value.code == 112:
                reference = int.from_bytes(value.payload, "big")
                if reference not in self.references:
                    raise FormatError(f"undefined structured-clone reference {reference}")
                value = self.references[reference]
            elif value.code == 0:
                return None
            else:
                return value
        return value

    def objects(self):
        scene = self.unwrap(self.root.get("scene", {}))
        pending = [(v, None, 0) for v in reversed(self.unwrap(scene.get("objects", [])))]
        visited = set()
        while pending:
            node, parent, depth = pending.pop()
            node = self.unwrap(node)
            if id(node) in visited:
                raise FormatError("scene hierarchy contains a cycle or repeated node")
            visited.add(id(node))
            data = self.unwrap(node.get("data", {}))
            geometry = self.unwrap(data.get("geometry", {}))
            geometry_data = self.unwrap(geometry.get("data", {})) if isinstance(geometry, dict) else {}
            yield {
                "id": node.get("id"), "parent": parent, "depth": depth,
                "name": data.get("name"), "type": data.get("type"),
                "geometry": geometry.get("type") if isinstance(geometry, dict) else None,
                "draco": isinstance(geometry_data, dict) and self.unwrap(geometry_data.get("draco")) is not None,
            }
            children = self.unwrap(node.get("children", []))
            pending.extend((v, node.get("id"), depth + 1) for v in reversed(children))

    def summary(self):
        objects = list(self.objects())
        shared = self.unwrap(self.root.get("shared", {}))
        collections = {}
        for key, value in shared.items():
            value = self.unwrap(value)
            collections[key] = len(value) if isinstance(value, (list, dict)) else None
        return {
            "schema": self.root.get("schema"), "version": self.root.get("version"),
            "root_keys": list(self.root), "objects": len(objects),
            "object_types": dict(Counter(v["type"] for v in objects)),
            "geometry_types": dict(Counter(v["geometry"] for v in objects if v["geometry"])),
            "draco_meshes": sum(v["draco"] for v in objects),
            "shared_collections": collections,
            "reference_definitions": len(self.references),
            "binary_media_signatures": dict(self.media),
            "data_uri_prefixes": dict(self.data_uris),
            "large_strings": len(self.large_strings),
            "large_string_characters": sum(self.large_strings),
            "largest_string_characters": max(self.large_strings, default=0),
        }


# Source module: splineformat/__main__.py
import argparse
import hashlib
import json
from pathlib import Path
import sys



def read_scene(filename):
    raw = Path(filename).read_bytes()
    decoder = Decoder(raw)
    root = decoder.decode()
    if not isinstance(root, dict) or not {"scene", "schema"} <= root.keys():
        raise FormatError("decoded root is not a supported Spline scene")
    info = {
        "file": str(filename), "bytes": len(raw),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "consumed_bytes": decoder.offset,
        "extensions": {str(k): v for k, v in sorted(decoder.extensions.items())},
        "record_definitions": decoder.record_definitions,
        "binary_values": decoder.binary_count, "binary_bytes": decoder.binary_bytes,
    }
    return root, info


def dump_json(value, path):
    with Path(path).open("w", encoding="utf-8") as stream:
        json.dump(value, stream, indent=2, ensure_ascii=False, allow_nan=False)
        stream.write("\n")


def main():
    parser = argparse.ArgumentParser(description="Inspect and round-trip the supplied .splinecode dialect")
    sub = parser.add_subparsers(dest="command", required=True)
    inspect = sub.add_parser("inspect", help="print document inventory as JSON")
    inspect.add_argument("input", type=Path)
    inspect.add_argument("--output", type=Path)
    objects = sub.add_parser("objects", help="list object names, IDs, parents and geometry")
    objects.add_argument("input", type=Path)
    objects.add_argument("--output", type=Path)
    decode = sub.add_parser("decode", help="export reversible JSON and embedded resources")
    decode.add_argument("input", type=Path)
    decode.add_argument("output", type=Path, help="new output directory")
    encode = sub.add_parser("encode", help="rebuild a scene from decoded scene.json")
    encode.add_argument("input", type=Path, help="path to scene.json")
    encode.add_argument("output", type=Path, help="new .splinecode file")
    args = parser.parse_args()
    try:
        if args.command == "decode" and args.output.exists():
            raise FormatError(f"output already exists: {args.output}")
        if args.command == "encode":
            if args.output.exists():
                raise FormatError(f"output already exists: {args.output}")
            with args.input.open(encoding="utf-8") as stream:
                document = json.load(stream)
            if document.get("format") != "splineformat-json-v1":
                raise FormatError("unsupported JSON document format")
            root = JsonImport(args.input.parent).convert(document["document"])
            with args.output.open("xb") as stream:
                Encoder(stream).encode(root)
            print(json.dumps({"file": str(args.output), "bytes": args.output.stat().st_size}))
            return
        root, info = read_scene(args.input)
        view = SceneView(root)
        if args.command == "objects":
            result = list(view.objects())
        else:
            result = {**info, **view.summary()}
        if args.command == "decode":
            args.output.mkdir(parents=True, exist_ok=False)
            export = JsonExport(args.output)
            document = export.convert(root)
            dump_json({"format": "splineformat-json-v1", "document": document}, args.output / "scene.json")
            dump_json(result, args.output / "summary.json")
            dump_json(list(view.objects()), args.output / "objects.json")
            dump_json(list(export.assets.values()), args.output / "assets.json")
            print(json.dumps({"directory": str(args.output), "unique_assets": len(export.assets), "objects": result["objects"]}))
        elif args.output:
            dump_json(result, args.output)
        else:
            print(json.dumps(result, indent=2, ensure_ascii=False, allow_nan=False))
    except (OSError, ValueError, KeyError, TypeError, RecursionError) as error:
        parser.exit(1, f"splineformat: {error}\n")


if __name__ == "__main__":
    main()
